### ISSUE TITLE
Remove "semver" from danger patterns

### ISSUE THREAD

**Issue by jehy** [KyleRoss/modclean#19]
semver is a popular module for checking package versions www.npmjs.com/package/semver and removing is will obviously do harm - and I don't think it can be useful.

**Comment by KyleRoss** [comment]
The reason it was added is due to some packages containing a `semver` file in the root. The number of packages are limited with this file, so it may be a possibility to remove it, but the reason it was added to "danger" is because of the semver package.

I will think about this and see if it's something worth changing in the next release.

**Comment by KyleRoss** [comment]
I have confirmed on the latest alpha version that the `semver` module is no longer being removed without needing to remove the pattern.
